#!/usr/bin/env bash

set -f -o pipefail

# source lib/logger
source tests/lib/logger_silent
source lib/http_helpers
source lib/parse_path
source lib/internal_commands
# source lib/docker
source tests/lib/docker_mock
# source lib/docker_request
source tests/lib/docker_request_mock
source lib/main

source tests/lib/assert.sh/assert.sh

: ${DOCKER_NAMESPACE:="nasoym"}

no_auth=1
assert "echo -e \"GET /9090/0.0.1/foo/bar/bla HTTP/1.1\n\" | main" "HTTP/1.0 200 Ok\nResponseHeader: Value\n\nfoo 0.0.1 9090\nGET /bar/bla HTTP/1.1"
assert 'echo -e "GET /foo/bar HTTP/1.1\n" | main' "HTTP/1.0 200 Ok\nResponseHeader: Value\n\nfoo latest -\nGET /bar HTTP/1.1"

no_auth=0
assert 'echo -e "GET /foo/bar HTTP/1.1\n" | main | tr -d "\r"' "HTTP/1.0 401 Unauthorized"

assert_end tests

