#!/usr/bin/env bash

set -ef -o pipefail

function docker_remove_all_containers() {
  docker_container_id="$(docker ps -a --format "{{.ID}}" || true)"
  echo "docker_container_id:${docker_container_id}"
  for container_id in $docker_container_id; do
    echo "remove container: ${container_id}"
    docker rm -f ${container_id}
  done
}

function docker_stop_all_containers() {
  docker_container_id="$(docker ps -f status=running --format "{{.ID}}" || true)"
  echo "docker_container_id:${docker_container_id}"
  for container_id in $docker_container_id; do
    echo "stop container: ${container_id}"
    docker stop ${container_id}
  done
}

function docker_update_all_containers() {
  images_to_update="$(max_time_diff=120 ./dockerhub_list)"
  echo "images_to_update:$images_to_update"

  DOCKER_NAMESPACE="nasoym"
  for docker_repository in $images_to_update; do
    echo ">>>$docker_repository"
    docker_container_id="$(docker ps -f ancestor=${DOCKER_NAMESPACE}/${docker_repository} --format "{{.ID}}" || true)"
    echo "active docker_container_id:${docker_container_id}"
    for container_id in $docker_container_id; do
      echo "remove container: ${container_id}"
      docker rm -f ${container_id}
    done
    docker pull ${DOCKER_NAMESPACE}/$docker_repository
  done
  # echo "$images_to_update" | parallel 'docker pull nasoym/{}'
  # docker_image_id="$(docker ps -f status=running -f ancestor=${DOCKER_NAMESPACE}/${docker_repository}:${docker_version} --format "{{.Image}}" || true)"
}

function docker_list_outdated() {
  dockerhub_list="$(curl -s "https://hub.docker.com/v2/repositories/nasoym/?page=1&page_size=10000")"

  remote_dockers="$(echo "$dockerhub_list" \
    | jq -c '.results|map({name,last_updated})[]' \
    | jq -c '.last_updated=(.last_updated|gsub("\\.[0-9]*Z$";"")|strptime("%Y-%m-%dT%H:%M:%S")|mktime)'
  )"

  local_dockers="$(docker images nasoym/* --format "{{.Repository}}:{{.Tag}} {{.CreatedAt}}" \
    | sort  \
    | sed \
      -e 's/ CET$//g' \
      -e 's/ CEST$//g' \
      -e 's/^\([^ ]*\) \(.*\)$/echo "\1 $(gdate -d "\2" +%s)"/ge' \
    | awk '{a[$1]=$2} END { for(i in a){ print i, a[i]} }' \
    | sort \
    | awk -F ' |:' '{a[$1]=$3} END {for(i in a){print i,a[i]}}' \
    | jq -c -R '.|split(" ")|{name:.[0]|gsub("^nasoym\/";""),last_updated:.[1]|tonumber,type:"local"}'
  )"

  : ${max_time_diff:="120"}

  echo -en "${remote_dockers}\n${local_dockers}" \
    | jq -s 'group_by(.name)' \
    | jq 'map({name:.[0].name,local:(.[]|select(.type=="local").last_updated),remote:(.[]|select(has("type")|not).last_updated)})' \
    | jq 'map(.diff=(.remote-.local))' \
    | jq "map(select(.diff > ${max_time_diff}))" \
    | jq -r 'map(.name)[]'

}

if [[ ${BASH_SOURCE[0]} != $0 ]]; then
  export -f docker_remove_all_containers
  export -f docker_stop_all_containers
  export -f docker_update_all_containers
  export -f docker_list_outdated
else
  main "${@}"
  exit $?
fi
