#!/usr/bin/env bash

function log() {
  if [[ -n "$LOG_FILE" ]];then
    echo "$(date +%FT%T) [$$] $@" >>${LOG_FILE}
  else
    echo "$(date +%FT%T) [$$] $@" >&2
  fi
}

# TODO check existence of log file, and create directory

