#!/usr/bin/env bash

function upper() { echo "$@" | tr '[:lower:]' '[:upper:]'; }

function parse_headers() {
  local HEADER_KEY HEADER_VALUE HEADER_LINE
  while read -r HEADER_LINE; do 
    HEADER_LINE="$(echo "$HEADER_LINE" | tr -d '\r')"
    [[ "$HEADER_LINE" =~ ^$ ]]&& { 
      break; 
    } 
    HEADER_KEY="${HEADER_LINE/%: */}"
    HEADER_KEY="$(upper ${HEADER_KEY//-/_} )"
    HEADER_VALUE="${HEADER_LINE/#*: /}"
    declare -g -x "REQUEST_HEADER_${HEADER_KEY}"="$HEADER_VALUE"
  done
}

